version: '3.8'

services:
  back:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_HOST=mysql-server
      - MYSQL_USER=carrental
      - MYSQL_PASSWORD=carrental
    depends_on:
      - mysql-server

  front:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - back

  mysql-server:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=carrental
      - MYSQL_USER=carrental
      - MYSQL_PASSWORD=carrental
